require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Rails:
  Enabled: true

Documentation:
  Enabled: false

# frozen_string_literal のコメントをfalse
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  MinNameLength: 1

Metrics/MethodLength:
  Enabled: false
