require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# frozen_string_literal のコメントをfalse
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
