version: '3.7'

services:
  db:
    image: postgres
    container_name: storage_note_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data:cached
  web:
    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && rails s"
    depends_on:
      - db
    volumes:
      - .:/storage_note:cached
      - bundle:/usr/local/bundle:cached
      - /storage_note/.git
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
      TZ: 'Asia/Tokyo'
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  bundle:
    driver: local
  data:
    driver: local
