production:
  FIREBASE_API_KEY: AIzaSyAnheal6A44QBks3OJHvIONT6wkGbl-x44
  FIREBASE_AUTH_DOMAIN: storage-note-dev.firebaseapp.com
  FIREBASE_PROJECT_ID: storage-note-dev
  FIREBASE_STORAGE_BUCKET: storage-note-dev.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 922020970665
  FIREBASE_APP_ID: 1:922020970665:web:0c3fde340c9413499429b8

development:
  FIREBASE_API_KEY: AIzaSyAnheal6A44QBks3OJHvIONT6wkGbl-x44
  FIREBASE_AUTH_DOMAIN: storage-note-dev.firebaseapp.com
  FIREBASE_PROJECT_ID: storage-note-dev
  FIREBASE_STORAGE_BUCKET: storage-note-dev.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 922020970665
  FIREBASE_APP_ID: 1:922020970665:web:0c3fde340c9413499429b8

test:
  FIREBASE_API_KEY: AIzaSyAnheal6A44QBks3OJHvIONT6wkGbl-x44
  FIREBASE_AUTH_DOMAIN: storage-note-dev.firebaseapp.com
  FIREBASE_PROJECT_ID: storage-note-dev
  FIREBASE_STORAGE_BUCKET: storage-note-dev.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 922020970665
  FIREBASE_APP_ID: 1:922020970665:web:0c3fde340c9413499429b8
